/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in cgh-processor
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Tables {

	/**
	 * The table cgh-processor.array
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Array ARRAY = uk.co.techblue.cgh.dnap.tables.Array.ARRAY;

	/**
	 * The table cgh-processor.arrayreference
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Arrayreference ARRAYREFERENCE = uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE;

	/**
	 * The table cgh-processor.audit
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Audit AUDIT = uk.co.techblue.cgh.dnap.tables.Audit.AUDIT;

	/**
	 * The table cgh-processor.baselineaverages
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Baselineaverages BASELINEAVERAGES = uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES;

	/**
	 * The table cgh-processor.DATABASECHANGELOG
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Databasechangelog DATABASECHANGELOG = uk.co.techblue.cgh.dnap.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table cgh-processor.DATABASECHANGELOGLOCK
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Databasechangeloglock DATABASECHANGELOGLOCK = uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table cgh-processor.region
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Region REGION = uk.co.techblue.cgh.dnap.tables.Region.REGION;

	/**
	 * The table cgh-processor.regionintensity
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Regionintensity REGIONINTENSITY = uk.co.techblue.cgh.dnap.tables.Regionintensity.REGIONINTENSITY;

	/**
	 * The table cgh-processor.regionintensityreference
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Regionintensityreference REGIONINTENSITYREFERENCE = uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE;

	/**
	 * The table cgh-processor.signal
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Signal SIGNAL = uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL;

	/**
	 * The table cgh-processor.signalreference
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Signalreference SIGNALREFERENCE = uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE;

	/**
	 * The table cgh-processor.zscore
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Zscore ZSCORE = uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE;
}
