/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ArrayreferenceDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference, java.lang.Long> {

	/**
	 * Create a new ArrayreferenceDao without any configuration
	 */
	public ArrayreferenceDao() {
		super(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference.class);
	}

	/**
	 * Create a new ArrayreferenceDao with an attached configuration
	 */
	public ArrayreferenceDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference object) {
		return object.getArrayid();
	}

	/**
	 * Fetch records that have <code>ArrayID IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByArrayid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.ARRAYID, values);
	}

	/**
	 * Fetch a unique record that has <code>ArrayID = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference fetchOneByArrayid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.ARRAYID, value);
	}

	/**
	 * Fetch records that have <code>FeatureExtractor_barcode IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByFeatureextractorBarcode(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.FEATUREEXTRACTOR_BARCODE, values);
	}

	/**
	 * Fetch records that have <code>AnyColorPrcntFeatNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByAnycolorprcntfeatnonunifol(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.ANYCOLORPRCNTFEATNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>DerivativeLR_spread IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByDerivativelrSpread(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.DERIVATIVELR_SPREAD, values);
	}

	/**
	 * Fetch records that have <code>g_Signal2Noise IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByGSignal2noise(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.G_SIGNAL2NOISE, values);
	}

	/**
	 * Fetch records that have <code>g_SignalIntensity IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByGSignalintensity(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.G_SIGNALINTENSITY, values);
	}

	/**
	 * Fetch records that have <code>r_Signal2Noise IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByRSignal2noise(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.R_SIGNAL2NOISE, values);
	}

	/**
	 * Fetch records that have <code>r_SignalIntensity IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByRSignalintensity(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.R_SIGNALINTENSITY, values);
	}

	/**
	 * Fetch records that have <code>Scan_Date IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByScanDate(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.SCAN_DATE, values);
	}

	/**
	 * Fetch records that have <code>ShortArrayId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByShortarrayid(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.SHORTARRAYID, values);
	}

	/**
	 * Fetch records that have <code>Protocol_Name IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByProtocolName(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.PROTOCOL_NAME, values);
	}

	/**
	 * Fetch records that have <code>Grid_GenomicBuild IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByGridGenomicbuild(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.GRID_GENOMICBUILD, values);
	}

	/**
	 * Fetch records that have <code>FeatureExtractor_ScanFileName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByFeatureextractorScanfilename(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.FEATUREEXTRACTOR_SCANFILENAME, values);
	}

	/**
	 * Fetch records that have <code>FeatureExtractor_DesignFileName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchByFeatureextractorDesignfilename(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.FEATUREEXTRACTOR_DESIGNFILENAME, values);
	}

	/**
	 * Fetch records that have <code>Sex IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Arrayreference> fetchBySex(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE.SEX, values);
	}
}
