/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class AuditDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, uk.co.techblue.cgh.dnap.tables.pojos.Audit, java.lang.Long> {

	/**
	 * Create a new AuditDao without any configuration
	 */
	public AuditDao() {
		super(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT, uk.co.techblue.cgh.dnap.tables.pojos.Audit.class);
	}

	/**
	 * Create a new AuditDao with an attached configuration
	 */
	public AuditDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT, uk.co.techblue.cgh.dnap.tables.pojos.Audit.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Audit object) {
		return object.getAuditId();
	}

	/**
	 * Fetch records that have <code>audit_id IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Audit> fetchByAuditId(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.AUDIT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>audit_id = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Audit fetchOneByAuditId(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.AUDIT_ID, value);
	}

	/**
	 * Fetch records that have <code>filename IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Audit> fetchByFilename(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.FILENAME, values);
	}

	/**
	 * Fetch records that have <code>processed_date IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Audit> fetchByProcessedDate(java.sql.Timestamp... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.PROCESSED_DATE, values);
	}

	/**
	 * Fetch records that have <code>processed IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Audit> fetchByProcessed(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.PROCESSED, values);
	}
}
