/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class DatabasechangeloglockDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord, uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock, java.lang.Integer> {

	/**
	 * Create a new DatabasechangeloglockDao without any configuration
	 */
	public DatabasechangeloglockDao() {
		super(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK, uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock.class);
	}

	/**
	 * Create a new DatabasechangeloglockDao with an attached configuration
	 */
	public DatabasechangeloglockDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK, uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock> fetchById(java.lang.Integer... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock fetchOneById(java.lang.Integer value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.ID, value);
	}

	/**
	 * Fetch records that have <code>LOCKED IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock> fetchByLocked(java.lang.Byte... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.LOCKED, values);
	}

	/**
	 * Fetch records that have <code>LOCKGRANTED IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock> fetchByLockgranted(java.sql.Timestamp... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.LOCKGRANTED, values);
	}

	/**
	 * Fetch records that have <code>LOCKEDBY IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Databasechangeloglock> fetchByLockedby(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.LOCKEDBY, values);
	}
}
