/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class RegionintensityreferenceDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference, java.lang.Long> {

	/**
	 * Create a new RegionintensityreferenceDao without any configuration
	 */
	public RegionintensityreferenceDao() {
		super(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference.class);
	}

	/**
	 * Create a new RegionintensityreferenceDao with an attached configuration
	 */
	public RegionintensityreferenceDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference object) {
		return object.getRegionintensityid();
	}

	/**
	 * Fetch records that have <code>RegionIntensityId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByRegionintensityid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.REGIONINTENSITYID, values);
	}

	/**
	 * Fetch a unique record that has <code>RegionIntensityId = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference fetchOneByRegionintensityid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.REGIONINTENSITYID, value);
	}

	/**
	 * Fetch records that have <code>RegionId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByRegionid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.REGIONID, values);
	}

	/**
	 * Fetch records that have <code>MeanGreenSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMeangreensignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEANGREENSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>MedianGreenSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMediangreensignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEDIANGREENSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>MeanRedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMeanredsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEANREDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>MedianRedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMedianredsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEDIANREDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>MeanLogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMeanlogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEANLOGRATIO, values);
	}

	/**
	 * Fetch records that have <code>MedianLogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByMedianlogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.MEDIANLOGRATIO, values);
	}

	/**
	 * Fetch records that have <code>ArrayId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Regionintensityreference> fetchByArrayid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE.ARRAYID, values);
	}
}
