/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class RegionDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.RegionRecord, uk.co.techblue.cgh.dnap.tables.pojos.Region, java.lang.Long> {

	/**
	 * Create a new RegionDao without any configuration
	 */
	public RegionDao() {
		super(uk.co.techblue.cgh.dnap.tables.Region.REGION, uk.co.techblue.cgh.dnap.tables.pojos.Region.class);
	}

	/**
	 * Create a new RegionDao with an attached configuration
	 */
	public RegionDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Region.REGION, uk.co.techblue.cgh.dnap.tables.pojos.Region.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Region object) {
		return object.getRegionid();
	}

	/**
	 * Fetch records that have <code>RegionID IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Region> fetchByRegionid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Region.REGION.REGIONID, values);
	}

	/**
	 * Fetch a unique record that has <code>RegionID = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Region fetchOneByRegionid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Region.REGION.REGIONID, value);
	}

	/**
	 * Fetch records that have <code>Chromosome IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Region> fetchByChromosome(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Region.REGION.CHROMOSOME, values);
	}

	/**
	 * Fetch records that have <code>StartPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Region> fetchByStartposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Region.REGION.STARTPOSITION, values);
	}

	/**
	 * Fetch records that have <code>StopPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Region> fetchByStopposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Region.REGION.STOPPOSITION, values);
	}

	/**
	 * Fetch records that have <code>region IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Region> fetchByRegion(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Region.REGION.REGION_, values);
	}
}
