/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class SignalreferenceDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.SignalreferenceRecord, uk.co.techblue.cgh.dnap.tables.pojos.Signalreference, java.lang.Long> {

	/**
	 * Create a new SignalreferenceDao without any configuration
	 */
	public SignalreferenceDao() {
		super(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Signalreference.class);
	}

	/**
	 * Create a new SignalreferenceDao with an attached configuration
	 */
	public SignalreferenceDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE, uk.co.techblue.cgh.dnap.tables.pojos.Signalreference.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Signalreference object) {
		return object.getSignalid();
	}

	/**
	 * Fetch records that have <code>SignalId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchBySignalid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.SIGNALID, values);
	}

	/**
	 * Fetch a unique record that has <code>SignalId = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Signalreference fetchOneBySignalid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.SIGNALID, value);
	}

	/**
	 * Fetch records that have <code>ProbeName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByProbename(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.PROBENAME, values);
	}

	/**
	 * Fetch records that have <code>SystematicName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchBySystematicname(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.SYSTEMATICNAME, values);
	}

	/**
	 * Fetch records that have <code>LogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByLogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.LOGRATIO, values);
	}

	/**
	 * Fetch records that have <code>gProcessedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByGprocessedsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.GPROCESSEDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>rProcessedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByRprocessedsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.RPROCESSEDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>gIsSaturated IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByGissaturated(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.GISSATURATED, values);
	}

	/**
	 * Fetch records that have <code>rIsSaturated IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByRissaturated(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.RISSATURATED, values);
	}

	/**
	 * Fetch records that have <code>gIsFeatNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByGisfeatnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.GISFEATNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>rIsFeatNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByRisfeatnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.RISFEATNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>gIsBGNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByGisbgnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.GISBGNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>rIsBGNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByRisbgnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.RISBGNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>Chromosome IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByChromosome(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.CHROMOSOME, values);
	}

	/**
	 * Fetch records that have <code>StartPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByStartposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.STARTPOSITION, values);
	}

	/**
	 * Fetch records that have <code>StopPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByStopposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.STOPPOSITION, values);
	}

	/**
	 * Fetch records that have <code>gIsWellAboveBG IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByGiswellabovebg(java.lang.Byte... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.GISWELLABOVEBG, values);
	}

	/**
	 * Fetch records that have <code>rIsWellAboveBG IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByRiswellabovebg(java.lang.Byte... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.RISWELLABOVEBG, values);
	}

	/**
	 * Fetch records that have <code>ArrayId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signalreference> fetchByArrayid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signalreference.SIGNALREFERENCE.ARRAYID, values);
	}
}
