/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class SignalDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.SignalRecord, uk.co.techblue.cgh.dnap.tables.pojos.Signal, java.lang.Long> {

	/**
	 * Create a new SignalDao without any configuration
	 */
	public SignalDao() {
		super(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL, uk.co.techblue.cgh.dnap.tables.pojos.Signal.class);
	}

	/**
	 * Create a new SignalDao with an attached configuration
	 */
	public SignalDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL, uk.co.techblue.cgh.dnap.tables.pojos.Signal.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Signal object) {
		return object.getSignalid();
	}

	/**
	 * Fetch records that have <code>SignalId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchBySignalid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.SIGNALID, values);
	}

	/**
	 * Fetch a unique record that has <code>SignalId = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Signal fetchOneBySignalid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.SIGNALID, value);
	}

	/**
	 * Fetch records that have <code>ProbeName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByProbename(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.PROBENAME, values);
	}

	/**
	 * Fetch records that have <code>SystematicName IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchBySystematicname(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.SYSTEMATICNAME, values);
	}

	/**
	 * Fetch records that have <code>LogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByLogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.LOGRATIO, values);
	}

	/**
	 * Fetch records that have <code>gProcessedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByGprocessedsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.GPROCESSEDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>rProcessedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByRprocessedsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.RPROCESSEDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>gIsSaturated IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByGissaturated(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.GISSATURATED, values);
	}

	/**
	 * Fetch records that have <code>rIsSaturated IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByRissaturated(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.RISSATURATED, values);
	}

	/**
	 * Fetch records that have <code>gIsFeatNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByGisfeatnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.GISFEATNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>rIsFeatNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByRisfeatnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.RISFEATNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>gIsBGNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByGisbgnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.GISBGNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>rIsBGNonUnifOL IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByRisbgnonunifol(java.lang.Boolean... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.RISBGNONUNIFOL, values);
	}

	/**
	 * Fetch records that have <code>Chromosome IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByChromosome(java.lang.String... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.CHROMOSOME, values);
	}

	/**
	 * Fetch records that have <code>StartPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByStartposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.STARTPOSITION, values);
	}

	/**
	 * Fetch records that have <code>StopPosition IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByStopposition(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.STOPPOSITION, values);
	}

	/**
	 * Fetch records that have <code>gIsWellAboveBG IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByGiswellabovebg(java.lang.Byte... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.GISWELLABOVEBG, values);
	}

	/**
	 * Fetch records that have <code>rIsWellAboveBG IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByRiswellabovebg(java.lang.Byte... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.RISWELLABOVEBG, values);
	}

	/**
	 * Fetch records that have <code>ArrayId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Signal> fetchByArrayid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Signal.SIGNAL.ARRAYID, values);
	}
}
