/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ZscoreDao extends org.jooq.impl.DAOImpl<uk.co.techblue.cgh.dnap.tables.records.ZscoreRecord, uk.co.techblue.cgh.dnap.tables.pojos.Zscore, java.lang.Long> {

	/**
	 * Create a new ZscoreDao without any configuration
	 */
	public ZscoreDao() {
		super(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE, uk.co.techblue.cgh.dnap.tables.pojos.Zscore.class);
	}

	/**
	 * Create a new ZscoreDao with an attached configuration
	 */
	public ZscoreDao(org.jooq.Configuration configuration) {
		super(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE, uk.co.techblue.cgh.dnap.tables.pojos.Zscore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(uk.co.techblue.cgh.dnap.tables.pojos.Zscore object) {
		return object.getZscoreid();
	}

	/**
	 * Fetch records that have <code>ZScoreId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZscoreid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZSCOREID, values);
	}

	/**
	 * Fetch a unique record that has <code>ZScoreId = value</code>
	 */
	public uk.co.techblue.cgh.dnap.tables.pojos.Zscore fetchOneByZscoreid(java.lang.Long value) {
		return fetchOne(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZSCOREID, value);
	}

	/**
	 * Fetch records that have <code>RegionIntensityId IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByRegionintensityid(java.lang.Long... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.REGIONINTENSITYID, values);
	}

	/**
	 * Fetch records that have <code>ZMeanGreenSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmeangreensignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEANGREENSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>ZMedianGreenSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmediangreensignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEDIANGREENSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>ZMeanRedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmeanredsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEANREDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>ZMedianRedSignal IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmedianredsignal(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEDIANREDSIGNAL, values);
	}

	/**
	 * Fetch records that have <code>ZMeanLogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmeanlogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEANLOGRATIO, values);
	}

	/**
	 * Fetch records that have <code>ZMedianLogRatio IN (values)</code>
	 */
	public java.util.List<uk.co.techblue.cgh.dnap.tables.pojos.Zscore> fetchByZmedianlogratio(java.lang.Double... values) {
		return fetch(uk.co.techblue.cgh.dnap.tables.Zscore.ZSCORE.ZMEDIANLOGRATIO, values);
	}
}
