/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Arrayreference implements uk.co.techblue.cgh.dnap.tables.interfaces.IArrayreference {

	private static final long serialVersionUID = -1073881795;

	private java.lang.Long   arrayid;
	private java.lang.String featureextractorBarcode;
	private java.lang.Double anycolorprcntfeatnonunifol;
	private java.lang.Double derivativelrSpread;
	private java.lang.Double gSignal2noise;
	private java.lang.Double gSignalintensity;
	private java.lang.Double rSignal2noise;
	private java.lang.Double rSignalintensity;
	private java.lang.String scanDate;
	private java.lang.Double shortarrayid;
	private java.lang.String protocolName;
	private java.lang.String gridGenomicbuild;
	private java.lang.String featureextractorScanfilename;
	private java.lang.String featureextractorDesignfilename;
	private java.lang.String sex;

	@Override
	public java.lang.Long getArrayid() {
		return this.arrayid;
	}

	@Override
	public void setArrayid(java.lang.Long arrayid) {
		this.arrayid = arrayid;
	}

	@Override
	public java.lang.String getFeatureextractorBarcode() {
		return this.featureextractorBarcode;
	}

	@Override
	public void setFeatureextractorBarcode(java.lang.String featureextractorBarcode) {
		this.featureextractorBarcode = featureextractorBarcode;
	}

	@Override
	public java.lang.Double getAnycolorprcntfeatnonunifol() {
		return this.anycolorprcntfeatnonunifol;
	}

	@Override
	public void setAnycolorprcntfeatnonunifol(java.lang.Double anycolorprcntfeatnonunifol) {
		this.anycolorprcntfeatnonunifol = anycolorprcntfeatnonunifol;
	}

	@Override
	public java.lang.Double getDerivativelrSpread() {
		return this.derivativelrSpread;
	}

	@Override
	public void setDerivativelrSpread(java.lang.Double derivativelrSpread) {
		this.derivativelrSpread = derivativelrSpread;
	}

	@Override
	public java.lang.Double getGSignal2noise() {
		return this.gSignal2noise;
	}

	@Override
	public void setGSignal2noise(java.lang.Double gSignal2noise) {
		this.gSignal2noise = gSignal2noise;
	}

	@Override
	public java.lang.Double getGSignalintensity() {
		return this.gSignalintensity;
	}

	@Override
	public void setGSignalintensity(java.lang.Double gSignalintensity) {
		this.gSignalintensity = gSignalintensity;
	}

	@Override
	public java.lang.Double getRSignal2noise() {
		return this.rSignal2noise;
	}

	@Override
	public void setRSignal2noise(java.lang.Double rSignal2noise) {
		this.rSignal2noise = rSignal2noise;
	}

	@Override
	public java.lang.Double getRSignalintensity() {
		return this.rSignalintensity;
	}

	@Override
	public void setRSignalintensity(java.lang.Double rSignalintensity) {
		this.rSignalintensity = rSignalintensity;
	}

	@Override
	public java.lang.String getScanDate() {
		return this.scanDate;
	}

	@Override
	public void setScanDate(java.lang.String scanDate) {
		this.scanDate = scanDate;
	}

	@Override
	public java.lang.Double getShortarrayid() {
		return this.shortarrayid;
	}

	@Override
	public void setShortarrayid(java.lang.Double shortarrayid) {
		this.shortarrayid = shortarrayid;
	}

	@Override
	public java.lang.String getProtocolName() {
		return this.protocolName;
	}

	@Override
	public void setProtocolName(java.lang.String protocolName) {
		this.protocolName = protocolName;
	}

	@Override
	public java.lang.String getGridGenomicbuild() {
		return this.gridGenomicbuild;
	}

	@Override
	public void setGridGenomicbuild(java.lang.String gridGenomicbuild) {
		this.gridGenomicbuild = gridGenomicbuild;
	}

	@Override
	public java.lang.String getFeatureextractorScanfilename() {
		return this.featureextractorScanfilename;
	}

	@Override
	public void setFeatureextractorScanfilename(java.lang.String featureextractorScanfilename) {
		this.featureextractorScanfilename = featureextractorScanfilename;
	}

	@Override
	public java.lang.String getFeatureextractorDesignfilename() {
		return this.featureextractorDesignfilename;
	}

	@Override
	public void setFeatureextractorDesignfilename(java.lang.String featureextractorDesignfilename) {
		this.featureextractorDesignfilename = featureextractorDesignfilename;
	}

	@Override
	public java.lang.String getSex() {
		return this.sex;
	}

	@Override
	public void setSex(java.lang.String sex) {
		this.sex = sex;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IArrayreference from) {
		setArrayid(from.getArrayid());
		setFeatureextractorBarcode(from.getFeatureextractorBarcode());
		setAnycolorprcntfeatnonunifol(from.getAnycolorprcntfeatnonunifol());
		setDerivativelrSpread(from.getDerivativelrSpread());
		setGSignal2noise(from.getGSignal2noise());
		setGSignalintensity(from.getGSignalintensity());
		setRSignal2noise(from.getRSignal2noise());
		setRSignalintensity(from.getRSignalintensity());
		setScanDate(from.getScanDate());
		setShortarrayid(from.getShortarrayid());
		setProtocolName(from.getProtocolName());
		setGridGenomicbuild(from.getGridGenomicbuild());
		setFeatureextractorScanfilename(from.getFeatureextractorScanfilename());
		setFeatureextractorDesignfilename(from.getFeatureextractorDesignfilename());
		setSex(from.getSex());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IArrayreference> E into(E into) {
		into.from(this);
		return into;
	}
}
