/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Audit implements uk.co.techblue.cgh.dnap.tables.interfaces.IAudit {

	private static final long serialVersionUID = 1735924325;

	private java.lang.Long     auditId;
	private java.lang.String   filename;
	private java.sql.Timestamp processedDate;
	private java.lang.Boolean  processed;

	@Override
	public java.lang.Long getAuditId() {
		return this.auditId;
	}

	@Override
	public void setAuditId(java.lang.Long auditId) {
		this.auditId = auditId;
	}

	@Override
	public java.lang.String getFilename() {
		return this.filename;
	}

	@Override
	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	@Override
	public java.sql.Timestamp getProcessedDate() {
		return this.processedDate;
	}

	@Override
	public void setProcessedDate(java.sql.Timestamp processedDate) {
		this.processedDate = processedDate;
	}

	@Override
	public java.lang.Boolean getProcessed() {
		return this.processed;
	}

	@Override
	public void setProcessed(java.lang.Boolean processed) {
		this.processed = processed;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IAudit from) {
		setAuditId(from.getAuditId());
		setFilename(from.getFilename());
		setProcessedDate(from.getProcessedDate());
		setProcessed(from.getProcessed());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IAudit> E into(E into) {
		into.from(this);
		return into;
	}
}
