/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Baselineaverages implements uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages {

	private static final long serialVersionUID = 1373893726;

	private java.lang.Long   baselineaveragesid;
	private java.lang.Long   regionid;
	private java.lang.String chromosome;
	private java.lang.Long   startposition;
	private java.lang.Long   stopposition;
	private java.lang.Double bmeangreensignal;
	private java.lang.Double bmeangreensignalsd;
	private java.lang.Double bmediangreensignal;
	private java.lang.Double bmediangreensignalsd;
	private java.lang.Double bmeanredsignal;
	private java.lang.Double bmeanredsignalsd;
	private java.lang.Double bmedianredsignal;
	private java.lang.Double bmedianredsignalsd;
	private java.lang.Double bmeanlogratio;
	private java.lang.Double bmeanlogratiosd;
	private java.lang.Double bmedianlogratio;
	private java.lang.Double bmedianlogratiosd;

	@Override
	public java.lang.Long getBaselineaveragesid() {
		return this.baselineaveragesid;
	}

	@Override
	public void setBaselineaveragesid(java.lang.Long baselineaveragesid) {
		this.baselineaveragesid = baselineaveragesid;
	}

	@Override
	public java.lang.Long getRegionid() {
		return this.regionid;
	}

	@Override
	public void setRegionid(java.lang.Long regionid) {
		this.regionid = regionid;
	}

	@Override
	public java.lang.String getChromosome() {
		return this.chromosome;
	}

	@Override
	public void setChromosome(java.lang.String chromosome) {
		this.chromosome = chromosome;
	}

	@Override
	public java.lang.Long getStartposition() {
		return this.startposition;
	}

	@Override
	public void setStartposition(java.lang.Long startposition) {
		this.startposition = startposition;
	}

	@Override
	public java.lang.Long getStopposition() {
		return this.stopposition;
	}

	@Override
	public void setStopposition(java.lang.Long stopposition) {
		this.stopposition = stopposition;
	}

	@Override
	public java.lang.Double getBmeangreensignal() {
		return this.bmeangreensignal;
	}

	@Override
	public void setBmeangreensignal(java.lang.Double bmeangreensignal) {
		this.bmeangreensignal = bmeangreensignal;
	}

	@Override
	public java.lang.Double getBmeangreensignalsd() {
		return this.bmeangreensignalsd;
	}

	@Override
	public void setBmeangreensignalsd(java.lang.Double bmeangreensignalsd) {
		this.bmeangreensignalsd = bmeangreensignalsd;
	}

	@Override
	public java.lang.Double getBmediangreensignal() {
		return this.bmediangreensignal;
	}

	@Override
	public void setBmediangreensignal(java.lang.Double bmediangreensignal) {
		this.bmediangreensignal = bmediangreensignal;
	}

	@Override
	public java.lang.Double getBmediangreensignalsd() {
		return this.bmediangreensignalsd;
	}

	@Override
	public void setBmediangreensignalsd(java.lang.Double bmediangreensignalsd) {
		this.bmediangreensignalsd = bmediangreensignalsd;
	}

	@Override
	public java.lang.Double getBmeanredsignal() {
		return this.bmeanredsignal;
	}

	@Override
	public void setBmeanredsignal(java.lang.Double bmeanredsignal) {
		this.bmeanredsignal = bmeanredsignal;
	}

	@Override
	public java.lang.Double getBmeanredsignalsd() {
		return this.bmeanredsignalsd;
	}

	@Override
	public void setBmeanredsignalsd(java.lang.Double bmeanredsignalsd) {
		this.bmeanredsignalsd = bmeanredsignalsd;
	}

	@Override
	public java.lang.Double getBmedianredsignal() {
		return this.bmedianredsignal;
	}

	@Override
	public void setBmedianredsignal(java.lang.Double bmedianredsignal) {
		this.bmedianredsignal = bmedianredsignal;
	}

	@Override
	public java.lang.Double getBmedianredsignalsd() {
		return this.bmedianredsignalsd;
	}

	@Override
	public void setBmedianredsignalsd(java.lang.Double bmedianredsignalsd) {
		this.bmedianredsignalsd = bmedianredsignalsd;
	}

	@Override
	public java.lang.Double getBmeanlogratio() {
		return this.bmeanlogratio;
	}

	@Override
	public void setBmeanlogratio(java.lang.Double bmeanlogratio) {
		this.bmeanlogratio = bmeanlogratio;
	}

	@Override
	public java.lang.Double getBmeanlogratiosd() {
		return this.bmeanlogratiosd;
	}

	@Override
	public void setBmeanlogratiosd(java.lang.Double bmeanlogratiosd) {
		this.bmeanlogratiosd = bmeanlogratiosd;
	}

	@Override
	public java.lang.Double getBmedianlogratio() {
		return this.bmedianlogratio;
	}

	@Override
	public void setBmedianlogratio(java.lang.Double bmedianlogratio) {
		this.bmedianlogratio = bmedianlogratio;
	}

	@Override
	public java.lang.Double getBmedianlogratiosd() {
		return this.bmedianlogratiosd;
	}

	@Override
	public void setBmedianlogratiosd(java.lang.Double bmedianlogratiosd) {
		this.bmedianlogratiosd = bmedianlogratiosd;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages from) {
		setBaselineaveragesid(from.getBaselineaveragesid());
		setRegionid(from.getRegionid());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
		setBmeangreensignal(from.getBmeangreensignal());
		setBmeangreensignalsd(from.getBmeangreensignalsd());
		setBmediangreensignal(from.getBmediangreensignal());
		setBmediangreensignalsd(from.getBmediangreensignalsd());
		setBmeanredsignal(from.getBmeanredsignal());
		setBmeanredsignalsd(from.getBmeanredsignalsd());
		setBmedianredsignal(from.getBmedianredsignal());
		setBmedianredsignalsd(from.getBmedianredsignalsd());
		setBmeanlogratio(from.getBmeanlogratio());
		setBmeanlogratiosd(from.getBmeanlogratiosd());
		setBmedianlogratio(from.getBmedianlogratio());
		setBmedianlogratiosd(from.getBmedianlogratiosd());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages> E into(E into) {
		into.from(this);
		return into;
	}
}
