/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Baselineaverages implements uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages {

	private static final long serialVersionUID = 1555306902;

	private java.lang.Long   baselineaveragesid;
	private java.lang.Long   regionid;
	private java.lang.Double bmeangreensignal;
	private java.lang.Double bmeangreensignalsd;
	private java.lang.Double bmediangreensignal;
	private java.lang.Double bmediangreensignalsd;
	private java.lang.Double bmeanredsignal;
	private java.lang.Double bmeanredsignalsd;
	private java.lang.Double bmedianredsignal;
	private java.lang.Double bmedianredsignalsd;
	private java.lang.Double bmeanlogratio;
	private java.lang.Double bmeanlogratiosd;
	private java.lang.Double bmedianlogratio;
	private java.lang.Double bmedianlogratiosd;
	private java.lang.Double bmeangreensignalM;
	private java.lang.Double bmeangreensignalsdM;
	private java.lang.Double bmediangreensignalM;
	private java.lang.Double bmediangreensignalsdM;
	private java.lang.Double bmeanredsignalM;
	private java.lang.Double bmeanredsignalsdM;
	private java.lang.Double bmedianredsignalM;
	private java.lang.Double bmedianredsignalsdM;
	private java.lang.Double bmeanlogratioM;
	private java.lang.Double bmeanlogratiosdM;
	private java.lang.Double bmedianlogratioM;
	private java.lang.Double bmedianlogratiosdM;

	@Override
	public java.lang.Long getBaselineaveragesid() {
		return this.baselineaveragesid;
	}

	@Override
	public void setBaselineaveragesid(java.lang.Long baselineaveragesid) {
		this.baselineaveragesid = baselineaveragesid;
	}

	@Override
	public java.lang.Long getRegionid() {
		return this.regionid;
	}

	@Override
	public void setRegionid(java.lang.Long regionid) {
		this.regionid = regionid;
	}

	@Override
	public java.lang.Double getBmeangreensignal() {
		return this.bmeangreensignal;
	}

	@Override
	public void setBmeangreensignal(java.lang.Double bmeangreensignal) {
		this.bmeangreensignal = bmeangreensignal;
	}

	@Override
	public java.lang.Double getBmeangreensignalsd() {
		return this.bmeangreensignalsd;
	}

	@Override
	public void setBmeangreensignalsd(java.lang.Double bmeangreensignalsd) {
		this.bmeangreensignalsd = bmeangreensignalsd;
	}

	@Override
	public java.lang.Double getBmediangreensignal() {
		return this.bmediangreensignal;
	}

	@Override
	public void setBmediangreensignal(java.lang.Double bmediangreensignal) {
		this.bmediangreensignal = bmediangreensignal;
	}

	@Override
	public java.lang.Double getBmediangreensignalsd() {
		return this.bmediangreensignalsd;
	}

	@Override
	public void setBmediangreensignalsd(java.lang.Double bmediangreensignalsd) {
		this.bmediangreensignalsd = bmediangreensignalsd;
	}

	@Override
	public java.lang.Double getBmeanredsignal() {
		return this.bmeanredsignal;
	}

	@Override
	public void setBmeanredsignal(java.lang.Double bmeanredsignal) {
		this.bmeanredsignal = bmeanredsignal;
	}

	@Override
	public java.lang.Double getBmeanredsignalsd() {
		return this.bmeanredsignalsd;
	}

	@Override
	public void setBmeanredsignalsd(java.lang.Double bmeanredsignalsd) {
		this.bmeanredsignalsd = bmeanredsignalsd;
	}

	@Override
	public java.lang.Double getBmedianredsignal() {
		return this.bmedianredsignal;
	}

	@Override
	public void setBmedianredsignal(java.lang.Double bmedianredsignal) {
		this.bmedianredsignal = bmedianredsignal;
	}

	@Override
	public java.lang.Double getBmedianredsignalsd() {
		return this.bmedianredsignalsd;
	}

	@Override
	public void setBmedianredsignalsd(java.lang.Double bmedianredsignalsd) {
		this.bmedianredsignalsd = bmedianredsignalsd;
	}

	@Override
	public java.lang.Double getBmeanlogratio() {
		return this.bmeanlogratio;
	}

	@Override
	public void setBmeanlogratio(java.lang.Double bmeanlogratio) {
		this.bmeanlogratio = bmeanlogratio;
	}

	@Override
	public java.lang.Double getBmeanlogratiosd() {
		return this.bmeanlogratiosd;
	}

	@Override
	public void setBmeanlogratiosd(java.lang.Double bmeanlogratiosd) {
		this.bmeanlogratiosd = bmeanlogratiosd;
	}

	@Override
	public java.lang.Double getBmedianlogratio() {
		return this.bmedianlogratio;
	}

	@Override
	public void setBmedianlogratio(java.lang.Double bmedianlogratio) {
		this.bmedianlogratio = bmedianlogratio;
	}

	@Override
	public java.lang.Double getBmedianlogratiosd() {
		return this.bmedianlogratiosd;
	}

	@Override
	public void setBmedianlogratiosd(java.lang.Double bmedianlogratiosd) {
		this.bmedianlogratiosd = bmedianlogratiosd;
	}

	@Override
	public java.lang.Double getBmeangreensignalM() {
		return this.bmeangreensignalM;
	}

	@Override
	public void setBmeangreensignalM(java.lang.Double bmeangreensignalM) {
		this.bmeangreensignalM = bmeangreensignalM;
	}

	@Override
	public java.lang.Double getBmeangreensignalsdM() {
		return this.bmeangreensignalsdM;
	}

	@Override
	public void setBmeangreensignalsdM(java.lang.Double bmeangreensignalsdM) {
		this.bmeangreensignalsdM = bmeangreensignalsdM;
	}

	@Override
	public java.lang.Double getBmediangreensignalM() {
		return this.bmediangreensignalM;
	}

	@Override
	public void setBmediangreensignalM(java.lang.Double bmediangreensignalM) {
		this.bmediangreensignalM = bmediangreensignalM;
	}

	@Override
	public java.lang.Double getBmediangreensignalsdM() {
		return this.bmediangreensignalsdM;
	}

	@Override
	public void setBmediangreensignalsdM(java.lang.Double bmediangreensignalsdM) {
		this.bmediangreensignalsdM = bmediangreensignalsdM;
	}

	@Override
	public java.lang.Double getBmeanredsignalM() {
		return this.bmeanredsignalM;
	}

	@Override
	public void setBmeanredsignalM(java.lang.Double bmeanredsignalM) {
		this.bmeanredsignalM = bmeanredsignalM;
	}

	@Override
	public java.lang.Double getBmeanredsignalsdM() {
		return this.bmeanredsignalsdM;
	}

	@Override
	public void setBmeanredsignalsdM(java.lang.Double bmeanredsignalsdM) {
		this.bmeanredsignalsdM = bmeanredsignalsdM;
	}

	@Override
	public java.lang.Double getBmedianredsignalM() {
		return this.bmedianredsignalM;
	}

	@Override
	public void setBmedianredsignalM(java.lang.Double bmedianredsignalM) {
		this.bmedianredsignalM = bmedianredsignalM;
	}

	@Override
	public java.lang.Double getBmedianredsignalsdM() {
		return this.bmedianredsignalsdM;
	}

	@Override
	public void setBmedianredsignalsdM(java.lang.Double bmedianredsignalsdM) {
		this.bmedianredsignalsdM = bmedianredsignalsdM;
	}

	@Override
	public java.lang.Double getBmeanlogratioM() {
		return this.bmeanlogratioM;
	}

	@Override
	public void setBmeanlogratioM(java.lang.Double bmeanlogratioM) {
		this.bmeanlogratioM = bmeanlogratioM;
	}

	@Override
	public java.lang.Double getBmeanlogratiosdM() {
		return this.bmeanlogratiosdM;
	}

	@Override
	public void setBmeanlogratiosdM(java.lang.Double bmeanlogratiosdM) {
		this.bmeanlogratiosdM = bmeanlogratiosdM;
	}

	@Override
	public java.lang.Double getBmedianlogratioM() {
		return this.bmedianlogratioM;
	}

	@Override
	public void setBmedianlogratioM(java.lang.Double bmedianlogratioM) {
		this.bmedianlogratioM = bmedianlogratioM;
	}

	@Override
	public java.lang.Double getBmedianlogratiosdM() {
		return this.bmedianlogratiosdM;
	}

	@Override
	public void setBmedianlogratiosdM(java.lang.Double bmedianlogratiosdM) {
		this.bmedianlogratiosdM = bmedianlogratiosdM;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages from) {
		setBaselineaveragesid(from.getBaselineaveragesid());
		setRegionid(from.getRegionid());
		setBmeangreensignal(from.getBmeangreensignal());
		setBmeangreensignalsd(from.getBmeangreensignalsd());
		setBmediangreensignal(from.getBmediangreensignal());
		setBmediangreensignalsd(from.getBmediangreensignalsd());
		setBmeanredsignal(from.getBmeanredsignal());
		setBmeanredsignalsd(from.getBmeanredsignalsd());
		setBmedianredsignal(from.getBmedianredsignal());
		setBmedianredsignalsd(from.getBmedianredsignalsd());
		setBmeanlogratio(from.getBmeanlogratio());
		setBmeanlogratiosd(from.getBmeanlogratiosd());
		setBmedianlogratio(from.getBmedianlogratio());
		setBmedianlogratiosd(from.getBmedianlogratiosd());
		setBmeangreensignalM(from.getBmeangreensignalM());
		setBmeangreensignalsdM(from.getBmeangreensignalsdM());
		setBmediangreensignalM(from.getBmediangreensignalM());
		setBmediangreensignalsdM(from.getBmediangreensignalsdM());
		setBmeanredsignalM(from.getBmeanredsignalM());
		setBmeanredsignalsdM(from.getBmeanredsignalsdM());
		setBmedianredsignalM(from.getBmedianredsignalM());
		setBmedianredsignalsdM(from.getBmedianredsignalsdM());
		setBmeanlogratioM(from.getBmeanlogratioM());
		setBmeanlogratiosdM(from.getBmeanlogratiosdM());
		setBmedianlogratioM(from.getBmedianlogratioM());
		setBmedianlogratiosdM(from.getBmedianlogratiosdM());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages> E into(E into) {
		into.from(this);
		return into;
	}
}
