/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Databasechangelog implements uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangelog {

	private static final long serialVersionUID = -485130235;

	private java.lang.String   id;
	private java.lang.String   author;
	private java.lang.String   filename;
	private java.sql.Timestamp dateexecuted;
	private java.lang.Integer  orderexecuted;
	private java.lang.String   exectype;
	private java.lang.String   md5sum;
	private java.lang.String   description;
	private java.lang.String   comments;
	private java.lang.String   tag;
	private java.lang.String   liquibase;

	@Override
	public java.lang.String getId() {
		return this.id;
	}

	@Override
	public void setId(java.lang.String id) {
		this.id = id;
	}

	@Override
	public java.lang.String getAuthor() {
		return this.author;
	}

	@Override
	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	@Override
	public java.lang.String getFilename() {
		return this.filename;
	}

	@Override
	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	@Override
	public java.sql.Timestamp getDateexecuted() {
		return this.dateexecuted;
	}

	@Override
	public void setDateexecuted(java.sql.Timestamp dateexecuted) {
		this.dateexecuted = dateexecuted;
	}

	@Override
	public java.lang.Integer getOrderexecuted() {
		return this.orderexecuted;
	}

	@Override
	public void setOrderexecuted(java.lang.Integer orderexecuted) {
		this.orderexecuted = orderexecuted;
	}

	@Override
	public java.lang.String getExectype() {
		return this.exectype;
	}

	@Override
	public void setExectype(java.lang.String exectype) {
		this.exectype = exectype;
	}

	@Override
	public java.lang.String getMd5sum() {
		return this.md5sum;
	}

	@Override
	public void setMd5sum(java.lang.String md5sum) {
		this.md5sum = md5sum;
	}

	@Override
	public java.lang.String getDescription() {
		return this.description;
	}

	@Override
	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	@Override
	public java.lang.String getComments() {
		return this.comments;
	}

	@Override
	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	@Override
	public java.lang.String getTag() {
		return this.tag;
	}

	@Override
	public void setTag(java.lang.String tag) {
		this.tag = tag;
	}

	@Override
	public java.lang.String getLiquibase() {
		return this.liquibase;
	}

	@Override
	public void setLiquibase(java.lang.String liquibase) {
		this.liquibase = liquibase;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangelog from) {
		setId(from.getId());
		setAuthor(from.getAuthor());
		setFilename(from.getFilename());
		setDateexecuted(from.getDateexecuted());
		setOrderexecuted(from.getOrderexecuted());
		setExectype(from.getExectype());
		setMd5sum(from.getMd5sum());
		setDescription(from.getDescription());
		setComments(from.getComments());
		setTag(from.getTag());
		setLiquibase(from.getLiquibase());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangelog> E into(E into) {
		into.from(this);
		return into;
	}
}
