/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Databasechangeloglock implements uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangeloglock {

	private static final long serialVersionUID = -2051851740;

	private java.lang.Integer  id;
	private java.lang.Byte     locked;
	private java.sql.Timestamp lockgranted;
	private java.lang.String   lockedby;

	@Override
	public java.lang.Integer getId() {
		return this.id;
	}

	@Override
	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	@Override
	public java.lang.Byte getLocked() {
		return this.locked;
	}

	@Override
	public void setLocked(java.lang.Byte locked) {
		this.locked = locked;
	}

	@Override
	public java.sql.Timestamp getLockgranted() {
		return this.lockgranted;
	}

	@Override
	public void setLockgranted(java.sql.Timestamp lockgranted) {
		this.lockgranted = lockgranted;
	}

	@Override
	public java.lang.String getLockedby() {
		return this.lockedby;
	}

	@Override
	public void setLockedby(java.lang.String lockedby) {
		this.lockedby = lockedby;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangeloglock from) {
		setId(from.getId());
		setLocked(from.getLocked());
		setLockgranted(from.getLockgranted());
		setLockedby(from.getLockedby());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangeloglock> E into(E into) {
		into.from(this);
		return into;
	}
}
