/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Region implements uk.co.techblue.cgh.dnap.tables.interfaces.IRegion {

	private static final long serialVersionUID = -2004031691;

	private java.lang.Long   regionid;
	private java.lang.String chromosome;
	private java.lang.Long   startposition;
	private java.lang.Long   stopposition;
	private java.lang.String region;

	@Override
	public java.lang.Long getRegionid() {
		return this.regionid;
	}

	@Override
	public void setRegionid(java.lang.Long regionid) {
		this.regionid = regionid;
	}

	@Override
	public java.lang.String getChromosome() {
		return this.chromosome;
	}

	@Override
	public void setChromosome(java.lang.String chromosome) {
		this.chromosome = chromosome;
	}

	@Override
	public java.lang.Long getStartposition() {
		return this.startposition;
	}

	@Override
	public void setStartposition(java.lang.Long startposition) {
		this.startposition = startposition;
	}

	@Override
	public java.lang.Long getStopposition() {
		return this.stopposition;
	}

	@Override
	public void setStopposition(java.lang.Long stopposition) {
		this.stopposition = stopposition;
	}

	@Override
	public java.lang.String getRegion() {
		return this.region;
	}

	@Override
	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IRegion from) {
		setRegionid(from.getRegionid());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
		setRegion(from.getRegion());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IRegion> E into(E into) {
		into.from(this);
		return into;
	}
}
