/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Regionintensityreference implements uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensityreference {

	private static final long serialVersionUID = -1744715426;

	private java.lang.Long   regionintensityid;
	private java.lang.Long   regionid;
	private java.lang.Double meangreensignal;
	private java.lang.Double mediangreensignal;
	private java.lang.Double meanredsignal;
	private java.lang.Double medianredsignal;
	private java.lang.Double meanlogratio;
	private java.lang.Double medianlogratio;
	private java.lang.Long   arrayid;

	@Override
	public java.lang.Long getRegionintensityid() {
		return this.regionintensityid;
	}

	@Override
	public void setRegionintensityid(java.lang.Long regionintensityid) {
		this.regionintensityid = regionintensityid;
	}

	@Override
	public java.lang.Long getRegionid() {
		return this.regionid;
	}

	@Override
	public void setRegionid(java.lang.Long regionid) {
		this.regionid = regionid;
	}

	@Override
	public java.lang.Double getMeangreensignal() {
		return this.meangreensignal;
	}

	@Override
	public void setMeangreensignal(java.lang.Double meangreensignal) {
		this.meangreensignal = meangreensignal;
	}

	@Override
	public java.lang.Double getMediangreensignal() {
		return this.mediangreensignal;
	}

	@Override
	public void setMediangreensignal(java.lang.Double mediangreensignal) {
		this.mediangreensignal = mediangreensignal;
	}

	@Override
	public java.lang.Double getMeanredsignal() {
		return this.meanredsignal;
	}

	@Override
	public void setMeanredsignal(java.lang.Double meanredsignal) {
		this.meanredsignal = meanredsignal;
	}

	@Override
	public java.lang.Double getMedianredsignal() {
		return this.medianredsignal;
	}

	@Override
	public void setMedianredsignal(java.lang.Double medianredsignal) {
		this.medianredsignal = medianredsignal;
	}

	@Override
	public java.lang.Double getMeanlogratio() {
		return this.meanlogratio;
	}

	@Override
	public void setMeanlogratio(java.lang.Double meanlogratio) {
		this.meanlogratio = meanlogratio;
	}

	@Override
	public java.lang.Double getMedianlogratio() {
		return this.medianlogratio;
	}

	@Override
	public void setMedianlogratio(java.lang.Double medianlogratio) {
		this.medianlogratio = medianlogratio;
	}

	@Override
	public java.lang.Long getArrayid() {
		return this.arrayid;
	}

	@Override
	public void setArrayid(java.lang.Long arrayid) {
		this.arrayid = arrayid;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensityreference from) {
		setRegionintensityid(from.getRegionintensityid());
		setRegionid(from.getRegionid());
		setMeangreensignal(from.getMeangreensignal());
		setMediangreensignal(from.getMediangreensignal());
		setMeanredsignal(from.getMeanredsignal());
		setMedianredsignal(from.getMedianredsignal());
		setMeanlogratio(from.getMeanlogratio());
		setMedianlogratio(from.getMedianlogratio());
		setArrayid(from.getArrayid());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensityreference> E into(E into) {
		into.from(this);
		return into;
	}
}
