/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Regionintensity implements uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensity {

	private static final long serialVersionUID = 1639289637;

	private java.lang.Long   regionintensityid;
	private java.lang.Long   regionid;
	private java.lang.String chromosome;
	private java.lang.Long   startposition;
	private java.lang.Long   stopposition;
	private java.lang.String featureextractorBarcode;
	private java.lang.Double meangreensignal;
	private java.lang.Double mediangreensignal;
	private java.lang.Double meanredsignal;
	private java.lang.Double medianredsignal;
	private java.lang.Double meanlogratio;
	private java.lang.Double medianlogratio;

	@Override
	public java.lang.Long getRegionintensityid() {
		return this.regionintensityid;
	}

	@Override
	public void setRegionintensityid(java.lang.Long regionintensityid) {
		this.regionintensityid = regionintensityid;
	}

	@Override
	public java.lang.Long getRegionid() {
		return this.regionid;
	}

	@Override
	public void setRegionid(java.lang.Long regionid) {
		this.regionid = regionid;
	}

	@Override
	public java.lang.String getChromosome() {
		return this.chromosome;
	}

	@Override
	public void setChromosome(java.lang.String chromosome) {
		this.chromosome = chromosome;
	}

	@Override
	public java.lang.Long getStartposition() {
		return this.startposition;
	}

	@Override
	public void setStartposition(java.lang.Long startposition) {
		this.startposition = startposition;
	}

	@Override
	public java.lang.Long getStopposition() {
		return this.stopposition;
	}

	@Override
	public void setStopposition(java.lang.Long stopposition) {
		this.stopposition = stopposition;
	}

	@Override
	public java.lang.String getFeatureextractorBarcode() {
		return this.featureextractorBarcode;
	}

	@Override
	public void setFeatureextractorBarcode(java.lang.String featureextractorBarcode) {
		this.featureextractorBarcode = featureextractorBarcode;
	}

	@Override
	public java.lang.Double getMeangreensignal() {
		return this.meangreensignal;
	}

	@Override
	public void setMeangreensignal(java.lang.Double meangreensignal) {
		this.meangreensignal = meangreensignal;
	}

	@Override
	public java.lang.Double getMediangreensignal() {
		return this.mediangreensignal;
	}

	@Override
	public void setMediangreensignal(java.lang.Double mediangreensignal) {
		this.mediangreensignal = mediangreensignal;
	}

	@Override
	public java.lang.Double getMeanredsignal() {
		return this.meanredsignal;
	}

	@Override
	public void setMeanredsignal(java.lang.Double meanredsignal) {
		this.meanredsignal = meanredsignal;
	}

	@Override
	public java.lang.Double getMedianredsignal() {
		return this.medianredsignal;
	}

	@Override
	public void setMedianredsignal(java.lang.Double medianredsignal) {
		this.medianredsignal = medianredsignal;
	}

	@Override
	public java.lang.Double getMeanlogratio() {
		return this.meanlogratio;
	}

	@Override
	public void setMeanlogratio(java.lang.Double meanlogratio) {
		this.meanlogratio = meanlogratio;
	}

	@Override
	public java.lang.Double getMedianlogratio() {
		return this.medianlogratio;
	}

	@Override
	public void setMedianlogratio(java.lang.Double medianlogratio) {
		this.medianlogratio = medianlogratio;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensity from) {
		setRegionintensityid(from.getRegionintensityid());
		setRegionid(from.getRegionid());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
		setFeatureextractorBarcode(from.getFeatureextractorBarcode());
		setMeangreensignal(from.getMeangreensignal());
		setMediangreensignal(from.getMediangreensignal());
		setMeanredsignal(from.getMeanredsignal());
		setMedianredsignal(from.getMedianredsignal());
		setMeanlogratio(from.getMeanlogratio());
		setMedianlogratio(from.getMedianlogratio());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IRegionintensity> E into(E into) {
		into.from(this);
		return into;
	}
}
