/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Signal implements uk.co.techblue.cgh.dnap.tables.interfaces.ISignal {

	private static final long serialVersionUID = 1815770554;

	private java.lang.Long    signalid;
	private java.lang.String  probename;
	private java.lang.String  systematicname;
	private java.lang.Double  logratio;
	private java.lang.Double  gprocessedsignal;
	private java.lang.Double  rprocessedsignal;
	private java.lang.Boolean gissaturated;
	private java.lang.Boolean rissaturated;
	private java.lang.Boolean gisfeatnonunifol;
	private java.lang.Boolean risfeatnonunifol;
	private java.lang.Boolean gisbgnonunifol;
	private java.lang.Boolean risbgnonunifol;
	private java.lang.String  featureextractorBarcode;
	private java.lang.String  chromosome;
	private java.lang.Long    startposition;
	private java.lang.Long    stopposition;

	@Override
	public java.lang.Long getSignalid() {
		return this.signalid;
	}

	@Override
	public void setSignalid(java.lang.Long signalid) {
		this.signalid = signalid;
	}

	@Override
	public java.lang.String getProbename() {
		return this.probename;
	}

	@Override
	public void setProbename(java.lang.String probename) {
		this.probename = probename;
	}

	@Override
	public java.lang.String getSystematicname() {
		return this.systematicname;
	}

	@Override
	public void setSystematicname(java.lang.String systematicname) {
		this.systematicname = systematicname;
	}

	@Override
	public java.lang.Double getLogratio() {
		return this.logratio;
	}

	@Override
	public void setLogratio(java.lang.Double logratio) {
		this.logratio = logratio;
	}

	@Override
	public java.lang.Double getGprocessedsignal() {
		return this.gprocessedsignal;
	}

	@Override
	public void setGprocessedsignal(java.lang.Double gprocessedsignal) {
		this.gprocessedsignal = gprocessedsignal;
	}

	@Override
	public java.lang.Double getRprocessedsignal() {
		return this.rprocessedsignal;
	}

	@Override
	public void setRprocessedsignal(java.lang.Double rprocessedsignal) {
		this.rprocessedsignal = rprocessedsignal;
	}

	@Override
	public java.lang.Boolean getGissaturated() {
		return this.gissaturated;
	}

	@Override
	public void setGissaturated(java.lang.Boolean gissaturated) {
		this.gissaturated = gissaturated;
	}

	@Override
	public java.lang.Boolean getRissaturated() {
		return this.rissaturated;
	}

	@Override
	public void setRissaturated(java.lang.Boolean rissaturated) {
		this.rissaturated = rissaturated;
	}

	@Override
	public java.lang.Boolean getGisfeatnonunifol() {
		return this.gisfeatnonunifol;
	}

	@Override
	public void setGisfeatnonunifol(java.lang.Boolean gisfeatnonunifol) {
		this.gisfeatnonunifol = gisfeatnonunifol;
	}

	@Override
	public java.lang.Boolean getRisfeatnonunifol() {
		return this.risfeatnonunifol;
	}

	@Override
	public void setRisfeatnonunifol(java.lang.Boolean risfeatnonunifol) {
		this.risfeatnonunifol = risfeatnonunifol;
	}

	@Override
	public java.lang.Boolean getGisbgnonunifol() {
		return this.gisbgnonunifol;
	}

	@Override
	public void setGisbgnonunifol(java.lang.Boolean gisbgnonunifol) {
		this.gisbgnonunifol = gisbgnonunifol;
	}

	@Override
	public java.lang.Boolean getRisbgnonunifol() {
		return this.risbgnonunifol;
	}

	@Override
	public void setRisbgnonunifol(java.lang.Boolean risbgnonunifol) {
		this.risbgnonunifol = risbgnonunifol;
	}

	@Override
	public java.lang.String getFeatureextractorBarcode() {
		return this.featureextractorBarcode;
	}

	@Override
	public void setFeatureextractorBarcode(java.lang.String featureextractorBarcode) {
		this.featureextractorBarcode = featureextractorBarcode;
	}

	@Override
	public java.lang.String getChromosome() {
		return this.chromosome;
	}

	@Override
	public void setChromosome(java.lang.String chromosome) {
		this.chromosome = chromosome;
	}

	@Override
	public java.lang.Long getStartposition() {
		return this.startposition;
	}

	@Override
	public void setStartposition(java.lang.Long startposition) {
		this.startposition = startposition;
	}

	@Override
	public java.lang.Long getStopposition() {
		return this.stopposition;
	}

	@Override
	public void setStopposition(java.lang.Long stopposition) {
		this.stopposition = stopposition;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.ISignal from) {
		setSignalid(from.getSignalid());
		setProbename(from.getProbename());
		setSystematicname(from.getSystematicname());
		setLogratio(from.getLogratio());
		setGprocessedsignal(from.getGprocessedsignal());
		setRprocessedsignal(from.getRprocessedsignal());
		setGissaturated(from.getGissaturated());
		setRissaturated(from.getRissaturated());
		setGisfeatnonunifol(from.getGisfeatnonunifol());
		setRisfeatnonunifol(from.getRisfeatnonunifol());
		setGisbgnonunifol(from.getGisbgnonunifol());
		setRisbgnonunifol(from.getRisbgnonunifol());
		setFeatureextractorBarcode(from.getFeatureextractorBarcode());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.ISignal> E into(E into) {
		into.from(this);
		return into;
	}
}
