/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Zscore implements uk.co.techblue.cgh.dnap.tables.interfaces.IZscore {

	private static final long serialVersionUID = 590931839;

	private java.lang.Long   zscoreid;
	private java.lang.Long   regionintensityid;
	private java.lang.Double zmeangreensignal;
	private java.lang.Double zmediangreensignal;
	private java.lang.Double zmeanredsignal;
	private java.lang.Double zmedianredsignal;
	private java.lang.Double zmeanlogratio;
	private java.lang.Double zmedianlogratio;

	@Override
	public java.lang.Long getZscoreid() {
		return this.zscoreid;
	}

	@Override
	public void setZscoreid(java.lang.Long zscoreid) {
		this.zscoreid = zscoreid;
	}

	@Override
	public java.lang.Long getRegionintensityid() {
		return this.regionintensityid;
	}

	@Override
	public void setRegionintensityid(java.lang.Long regionintensityid) {
		this.regionintensityid = regionintensityid;
	}

	@Override
	public java.lang.Double getZmeangreensignal() {
		return this.zmeangreensignal;
	}

	@Override
	public void setZmeangreensignal(java.lang.Double zmeangreensignal) {
		this.zmeangreensignal = zmeangreensignal;
	}

	@Override
	public java.lang.Double getZmediangreensignal() {
		return this.zmediangreensignal;
	}

	@Override
	public void setZmediangreensignal(java.lang.Double zmediangreensignal) {
		this.zmediangreensignal = zmediangreensignal;
	}

	@Override
	public java.lang.Double getZmeanredsignal() {
		return this.zmeanredsignal;
	}

	@Override
	public void setZmeanredsignal(java.lang.Double zmeanredsignal) {
		this.zmeanredsignal = zmeanredsignal;
	}

	@Override
	public java.lang.Double getZmedianredsignal() {
		return this.zmedianredsignal;
	}

	@Override
	public void setZmedianredsignal(java.lang.Double zmedianredsignal) {
		this.zmedianredsignal = zmedianredsignal;
	}

	@Override
	public java.lang.Double getZmeanlogratio() {
		return this.zmeanlogratio;
	}

	@Override
	public void setZmeanlogratio(java.lang.Double zmeanlogratio) {
		this.zmeanlogratio = zmeanlogratio;
	}

	@Override
	public java.lang.Double getZmedianlogratio() {
		return this.zmedianlogratio;
	}

	@Override
	public void setZmedianlogratio(java.lang.Double zmedianlogratio) {
		this.zmedianlogratio = zmedianlogratio;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IZscore from) {
		setZscoreid(from.getZscoreid());
		setRegionintensityid(from.getRegionintensityid());
		setZmeangreensignal(from.getZmeangreensignal());
		setZmediangreensignal(from.getZmediangreensignal());
		setZmeanredsignal(from.getZmeanredsignal());
		setZmedianredsignal(from.getZmedianredsignal());
		setZmeanlogratio(from.getZmeanlogratio());
		setZmedianlogratio(from.getZmedianlogratio());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IZscore> E into(E into) {
		into.from(this);
		return into;
	}
}
