/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class AuditRecord extends org.jooq.impl.UpdatableRecordImpl<uk.co.techblue.cgh.dnap.tables.records.AuditRecord> implements org.jooq.Record4<java.lang.Long, java.lang.String, java.sql.Timestamp, java.lang.Boolean>, uk.co.techblue.cgh.dnap.tables.interfaces.IAudit {

	private static final long serialVersionUID = -1168753410;

	/**
	 * Setter for <code>cgh-processor.audit.audit_id</code>. 
	 */
	@Override
	public void setAuditId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cgh-processor.audit.audit_id</code>. 
	 */
	@Override
	public java.lang.Long getAuditId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cgh-processor.audit.filename</code>. 
	 */
	@Override
	public void setFilename(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cgh-processor.audit.filename</code>. 
	 */
	@Override
	public java.lang.String getFilename() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cgh-processor.audit.processed_date</code>. 
	 */
	@Override
	public void setProcessedDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cgh-processor.audit.processed_date</code>. 
	 */
	@Override
	public java.sql.Timestamp getProcessedDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>cgh-processor.audit.processed</code>. 
	 */
	@Override
	public void setProcessed(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cgh-processor.audit.processed</code>. 
	 */
	@Override
	public java.lang.Boolean getProcessed() {
		return (java.lang.Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.sql.Timestamp, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.sql.Timestamp, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.AUDIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.PROCESSED_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return uk.co.techblue.cgh.dnap.tables.Audit.AUDIT.PROCESSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getAuditId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getProcessedDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getProcessed();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IAudit from) {
		setAuditId(from.getAuditId());
		setFilename(from.getFilename());
		setProcessedDate(from.getProcessedDate());
		setProcessed(from.getProcessed());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IAudit> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuditRecord
	 */
	public AuditRecord() {
		super(uk.co.techblue.cgh.dnap.tables.Audit.AUDIT);
	}
}
