/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class BaselineaveragesRecord extends org.jooq.impl.UpdatableRecordImpl<uk.co.techblue.cgh.dnap.tables.records.BaselineaveragesRecord> implements org.jooq.Record17<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double>, uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages {

	private static final long serialVersionUID = 243240862;

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	@Override
	public void setBaselineaveragesid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	@Override
	public java.lang.Long getBaselineaveragesid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	@Override
	public void setRegionid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	@Override
	public java.lang.Long getRegionid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.Chromosome</code>. 
	 */
	@Override
	public void setChromosome(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.Chromosome</code>. 
	 */
	@Override
	public java.lang.String getChromosome() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.StartPosition</code>. 
	 */
	@Override
	public void setStartposition(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.StartPosition</code>. 
	 */
	@Override
	public java.lang.Long getStartposition() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.StopPosition</code>. 
	 */
	@Override
	public void setStopposition(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.StopPosition</code>. 
	 */
	@Override
	public java.lang.Long getStopposition() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	@Override
	public void setBmeangreensignal(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignal() {
		return (java.lang.Double) getValue(5);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	@Override
	public void setBmeangreensignalsd(java.lang.Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignalsd() {
		return (java.lang.Double) getValue(6);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	@Override
	public void setBmediangreensignal(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignal() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	@Override
	public void setBmediangreensignalsd(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignalsd() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	@Override
	public void setBmeanredsignal(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignal() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	@Override
	public void setBmeanredsignalsd(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignalsd() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	@Override
	public void setBmedianredsignal(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignal() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	@Override
	public void setBmedianredsignalsd(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignalsd() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	@Override
	public void setBmeanlogratio(java.lang.Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratio() {
		return (java.lang.Double) getValue(13);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	@Override
	public void setBmeanlogratiosd(java.lang.Double value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratiosd() {
		return (java.lang.Double) getValue(14);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	@Override
	public void setBmedianlogratio(java.lang.Double value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratio() {
		return (java.lang.Double) getValue(15);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	@Override
	public void setBmedianlogratiosd(java.lang.Double value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratiosd() {
		return (java.lang.Double) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double> fieldsRow() {
		return (org.jooq.Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double> valuesRow() {
		return (org.jooq.Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BASELINEAVERAGESID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.REGIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.CHROMOSOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.STARTPOSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.STOPPOSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field6() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANGREENSIGNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field7() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANGREENSIGNALSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field8() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANGREENSIGNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field9() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANGREENSIGNALSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field10() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANREDSIGNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field11() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANREDSIGNALSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field12() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANREDSIGNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field13() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANREDSIGNALSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field14() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANLOGRATIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field15() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEANLOGRATIOSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field16() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANLOGRATIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field17() {
		return uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES.BMEDIANLOGRATIOSD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getBaselineaveragesid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getRegionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getChromosome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getStartposition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getStopposition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value6() {
		return getBmeangreensignal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value7() {
		return getBmeangreensignalsd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value8() {
		return getBmediangreensignal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value9() {
		return getBmediangreensignalsd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value10() {
		return getBmeanredsignal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value11() {
		return getBmeanredsignalsd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value12() {
		return getBmedianredsignal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value13() {
		return getBmedianredsignalsd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value14() {
		return getBmeanlogratio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value15() {
		return getBmeanlogratiosd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value16() {
		return getBmedianlogratio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value17() {
		return getBmedianlogratiosd();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages from) {
		setBaselineaveragesid(from.getBaselineaveragesid());
		setRegionid(from.getRegionid());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
		setBmeangreensignal(from.getBmeangreensignal());
		setBmeangreensignalsd(from.getBmeangreensignalsd());
		setBmediangreensignal(from.getBmediangreensignal());
		setBmediangreensignalsd(from.getBmediangreensignalsd());
		setBmeanredsignal(from.getBmeanredsignal());
		setBmeanredsignalsd(from.getBmeanredsignalsd());
		setBmedianredsignal(from.getBmedianredsignal());
		setBmedianredsignalsd(from.getBmedianredsignalsd());
		setBmeanlogratio(from.getBmeanlogratio());
		setBmeanlogratiosd(from.getBmeanlogratiosd());
		setBmedianlogratio(from.getBmedianlogratio());
		setBmedianlogratiosd(from.getBmedianlogratiosd());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BaselineaveragesRecord
	 */
	public BaselineaveragesRecord() {
		super(uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES);
	}
}
