/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class BaselineaveragesRecord extends org.jooq.impl.UpdatableRecordImpl<uk.co.techblue.cgh.dnap.tables.records.BaselineaveragesRecord> implements uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages {

	private static final long serialVersionUID = -949400140;

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	@Override
	public void setBaselineaveragesid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	@Override
	public java.lang.Long getBaselineaveragesid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	@Override
	public void setRegionid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	@Override
	public java.lang.Long getRegionid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	@Override
	public void setBmeangreensignal(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignal() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	@Override
	public void setBmeangreensignalsd(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignalsd() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	@Override
	public void setBmediangreensignal(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignal() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	@Override
	public void setBmediangreensignalsd(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignalsd() {
		return (java.lang.Double) getValue(5);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	@Override
	public void setBmeanredsignal(java.lang.Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignal() {
		return (java.lang.Double) getValue(6);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	@Override
	public void setBmeanredsignalsd(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignalsd() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	@Override
	public void setBmedianredsignal(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignal() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	@Override
	public void setBmedianredsignalsd(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignalsd() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	@Override
	public void setBmeanlogratio(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratio() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	@Override
	public void setBmeanlogratiosd(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratiosd() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	@Override
	public void setBmedianlogratio(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratio() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	@Override
	public void setBmedianlogratiosd(java.lang.Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratiosd() {
		return (java.lang.Double) getValue(13);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignal_M</code>. 
	 */
	@Override
	public void setBmeangreensignalM(java.lang.Double value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignal_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignalM() {
		return (java.lang.Double) getValue(14);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD_M</code>. 
	 */
	@Override
	public void setBmeangreensignalsdM(java.lang.Double value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeangreensignalsdM() {
		return (java.lang.Double) getValue(15);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignal_M</code>. 
	 */
	@Override
	public void setBmediangreensignalM(java.lang.Double value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignal_M</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignalM() {
		return (java.lang.Double) getValue(16);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD_M</code>. 
	 */
	@Override
	public void setBmediangreensignalsdM(java.lang.Double value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmediangreensignalsdM() {
		return (java.lang.Double) getValue(17);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignal_M</code>. 
	 */
	@Override
	public void setBmeanredsignalM(java.lang.Double value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignal_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignalM() {
		return (java.lang.Double) getValue(18);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD_M</code>. 
	 */
	@Override
	public void setBmeanredsignalsdM(java.lang.Double value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeanredsignalsdM() {
		return (java.lang.Double) getValue(19);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignal_M</code>. 
	 */
	@Override
	public void setBmedianredsignalM(java.lang.Double value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignal_M</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignalM() {
		return (java.lang.Double) getValue(20);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD_M</code>. 
	 */
	@Override
	public void setBmedianredsignalsdM(java.lang.Double value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmedianredsignalsdM() {
		return (java.lang.Double) getValue(21);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatio_M</code>. 
	 */
	@Override
	public void setBmeanlogratioM(java.lang.Double value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatio_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratioM() {
		return (java.lang.Double) getValue(22);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD_M</code>. 
	 */
	@Override
	public void setBmeanlogratiosdM(java.lang.Double value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmeanlogratiosdM() {
		return (java.lang.Double) getValue(23);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatio_M</code>. 
	 */
	@Override
	public void setBmedianlogratioM(java.lang.Double value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatio_M</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratioM() {
		return (java.lang.Double) getValue(24);
	}

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD_M</code>. 
	 */
	@Override
	public void setBmedianlogratiosdM(java.lang.Double value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD_M</code>. 
	 */
	@Override
	public java.lang.Double getBmedianlogratiosdM() {
		return (java.lang.Double) getValue(25);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages from) {
		setBaselineaveragesid(from.getBaselineaveragesid());
		setRegionid(from.getRegionid());
		setBmeangreensignal(from.getBmeangreensignal());
		setBmeangreensignalsd(from.getBmeangreensignalsd());
		setBmediangreensignal(from.getBmediangreensignal());
		setBmediangreensignalsd(from.getBmediangreensignalsd());
		setBmeanredsignal(from.getBmeanredsignal());
		setBmeanredsignalsd(from.getBmeanredsignalsd());
		setBmedianredsignal(from.getBmedianredsignal());
		setBmedianredsignalsd(from.getBmedianredsignalsd());
		setBmeanlogratio(from.getBmeanlogratio());
		setBmeanlogratiosd(from.getBmeanlogratiosd());
		setBmedianlogratio(from.getBmedianlogratio());
		setBmedianlogratiosd(from.getBmedianlogratiosd());
		setBmeangreensignalM(from.getBmeangreensignalM());
		setBmeangreensignalsdM(from.getBmeangreensignalsdM());
		setBmediangreensignalM(from.getBmediangreensignalM());
		setBmediangreensignalsdM(from.getBmediangreensignalsdM());
		setBmeanredsignalM(from.getBmeanredsignalM());
		setBmeanredsignalsdM(from.getBmeanredsignalsdM());
		setBmedianredsignalM(from.getBmedianredsignalM());
		setBmedianredsignalsdM(from.getBmedianredsignalsdM());
		setBmeanlogratioM(from.getBmeanlogratioM());
		setBmeanlogratiosdM(from.getBmeanlogratiosdM());
		setBmedianlogratioM(from.getBmedianlogratioM());
		setBmedianlogratiosdM(from.getBmedianlogratiosdM());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BaselineaveragesRecord
	 */
	public BaselineaveragesRecord() {
		super(uk.co.techblue.cgh.dnap.tables.Baselineaverages.BASELINEAVERAGES);
	}
}
