/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class RegionRecord extends org.jooq.impl.UpdatableRecordImpl<uk.co.techblue.cgh.dnap.tables.records.RegionRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String>, uk.co.techblue.cgh.dnap.tables.interfaces.IRegion {

	private static final long serialVersionUID = 593025927;

	/**
	 * Setter for <code>cgh-processor.region.RegionID</code>. 
	 */
	@Override
	public void setRegionid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cgh-processor.region.RegionID</code>. 
	 */
	@Override
	public java.lang.Long getRegionid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cgh-processor.region.Chromosome</code>. it defines genes
	 */
	@Override
	public void setChromosome(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cgh-processor.region.Chromosome</code>. it defines genes
	 */
	@Override
	public java.lang.String getChromosome() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cgh-processor.region.StartPosition</code>. 
	 */
	@Override
	public void setStartposition(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cgh-processor.region.StartPosition</code>. 
	 */
	@Override
	public java.lang.Long getStartposition() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>cgh-processor.region.StopPosition</code>. 
	 */
	@Override
	public void setStopposition(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cgh-processor.region.StopPosition</code>. 
	 */
	@Override
	public java.lang.Long getStopposition() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>cgh-processor.region.region</code>. 
	 */
	@Override
	public void setRegion(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cgh-processor.region.region</code>. 
	 */
	@Override
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return uk.co.techblue.cgh.dnap.tables.Region.REGION.REGIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.co.techblue.cgh.dnap.tables.Region.REGION.CHROMOSOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return uk.co.techblue.cgh.dnap.tables.Region.REGION.STARTPOSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return uk.co.techblue.cgh.dnap.tables.Region.REGION.STOPPOSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return uk.co.techblue.cgh.dnap.tables.Region.REGION.REGION_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getRegionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getChromosome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getStartposition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getStopposition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getRegion();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IRegion from) {
		setRegionid(from.getRegionid());
		setChromosome(from.getChromosome());
		setStartposition(from.getStartposition());
		setStopposition(from.getStopposition());
		setRegion(from.getRegion());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IRegion> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RegionRecord
	 */
	public RegionRecord() {
		super(uk.co.techblue.cgh.dnap.tables.Region.REGION);
	}
}
