/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Arrayreference extends org.jooq.impl.TableImpl<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord> {

	private static final long serialVersionUID = -297182396;

	/**
	 * The singleton instance of <code>cgh-processor.arrayreference</code>
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Arrayreference ARRAYREFERENCE = new uk.co.techblue.cgh.dnap.tables.Arrayreference();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord> getRecordType() {
		return uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord.class;
	}

	/**
	 * The column <code>cgh-processor.arrayreference.ArrayID</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Long> ARRAYID = createField("ArrayID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cgh-processor.arrayreference.FeatureExtractor_barcode</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> FEATUREEXTRACTOR_BARCODE = createField("FeatureExtractor_barcode", org.jooq.impl.SQLDataType.VARCHAR.length(22), this);

	/**
	 * The column <code>cgh-processor.arrayreference.AnyColorPrcntFeatNonUnifOL</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> ANYCOLORPRCNTFEATNONUNIFOL = createField("AnyColorPrcntFeatNonUnifOL", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.DerivativeLR_spread</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> DERIVATIVELR_SPREAD = createField("DerivativeLR_spread", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.g_Signal2Noise</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> G_SIGNAL2NOISE = createField("g_Signal2Noise", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.g_SignalIntensity</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> G_SIGNALINTENSITY = createField("g_SignalIntensity", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.r_Signal2Noise</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> R_SIGNAL2NOISE = createField("r_Signal2Noise", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.r_SignalIntensity</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> R_SIGNALINTENSITY = createField("r_SignalIntensity", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.Scan_Date</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> SCAN_DATE = createField("Scan_Date", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>cgh-processor.arrayreference.ShortArrayId</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Double> SHORTARRAYID = createField("ShortArrayId", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.arrayreference.Protocol_Name</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> PROTOCOL_NAME = createField("Protocol_Name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>cgh-processor.arrayreference.Grid_GenomicBuild</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> GRID_GENOMICBUILD = createField("Grid_GenomicBuild", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>cgh-processor.arrayreference.FeatureExtractor_ScanFileName</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> FEATUREEXTRACTOR_SCANFILENAME = createField("FeatureExtractor_ScanFileName", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>cgh-processor.arrayreference.FeatureExtractor_DesignFileName</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> FEATUREEXTRACTOR_DESIGNFILENAME = createField("FeatureExtractor_DesignFileName", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>cgh-processor.arrayreference.Sex</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.String> SEX = createField("Sex", org.jooq.impl.SQLDataType.VARCHAR.length(1), this);

	/**
	 * Create a <code>cgh-processor.arrayreference</code> table reference
	 */
	public Arrayreference() {
		super("arrayreference", uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR);
	}

	/**
	 * Create an aliased <code>cgh-processor.arrayreference</code> table reference
	 */
	public Arrayreference(java.lang.String alias) {
		super(alias, uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR, uk.co.techblue.cgh.dnap.tables.Arrayreference.ARRAYREFERENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord, java.lang.Long> getIdentity() {
		return uk.co.techblue.cgh.dnap.Keys.IDENTITY_ARRAYREFERENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord> getPrimaryKey() {
		return uk.co.techblue.cgh.dnap.Keys.KEY_ARRAYREFERENCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.ArrayreferenceRecord>>asList(uk.co.techblue.cgh.dnap.Keys.KEY_ARRAYREFERENCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.co.techblue.cgh.dnap.tables.Arrayreference as(java.lang.String alias) {
		return new uk.co.techblue.cgh.dnap.tables.Arrayreference(alias);
	}
}
