/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Audit extends org.jooq.impl.TableImpl<uk.co.techblue.cgh.dnap.tables.records.AuditRecord> {

	private static final long serialVersionUID = -553891557;

	/**
	 * The singleton instance of <code>cgh-processor.audit</code>
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Audit AUDIT = new uk.co.techblue.cgh.dnap.tables.Audit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.co.techblue.cgh.dnap.tables.records.AuditRecord> getRecordType() {
		return uk.co.techblue.cgh.dnap.tables.records.AuditRecord.class;
	}

	/**
	 * The column <code>cgh-processor.audit.audit_id</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, java.lang.Long> AUDIT_ID = createField("audit_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cgh-processor.audit.filename</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, java.lang.String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>cgh-processor.audit.processed_date</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, java.sql.Timestamp> PROCESSED_DATE = createField("processed_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cgh-processor.audit.processed</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, java.lang.Boolean> PROCESSED = createField("processed", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>cgh-processor.audit</code> table reference
	 */
	public Audit() {
		super("audit", uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR);
	}

	/**
	 * Create an aliased <code>cgh-processor.audit</code> table reference
	 */
	public Audit(java.lang.String alias) {
		super(alias, uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR, uk.co.techblue.cgh.dnap.tables.Audit.AUDIT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.co.techblue.cgh.dnap.tables.records.AuditRecord, java.lang.Long> getIdentity() {
		return uk.co.techblue.cgh.dnap.Keys.IDENTITY_AUDIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.AuditRecord> getPrimaryKey() {
		return uk.co.techblue.cgh.dnap.Keys.KEY_AUDIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.AuditRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.AuditRecord>>asList(uk.co.techblue.cgh.dnap.Keys.KEY_AUDIT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.co.techblue.cgh.dnap.tables.Audit as(java.lang.String alias) {
		return new uk.co.techblue.cgh.dnap.tables.Audit(alias);
	}
}
