/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Databasechangeloglock extends org.jooq.impl.TableImpl<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = -492008082;

	/**
	 * The singleton instance of <code>cgh-processor.DATABASECHANGELOGLOCK</code>
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Databasechangeloglock DATABASECHANGELOGLOCK = new uk.co.techblue.cgh.dnap.tables.Databasechangeloglock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOGLOCK.ID</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKED</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord, java.lang.Byte> LOCKED = createField("LOCKED", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKGRANTED</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord, java.sql.Timestamp> LOCKGRANTED = createField("LOCKGRANTED", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKEDBY</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("LOCKEDBY", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>cgh-processor.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock() {
		super("DATABASECHANGELOGLOCK", uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR);
	}

	/**
	 * Create an aliased <code>cgh-processor.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock(java.lang.String alias) {
		super(alias, uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR, uk.co.techblue.cgh.dnap.tables.Databasechangeloglock.DATABASECHANGELOGLOCK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return uk.co.techblue.cgh.dnap.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangeloglockRecord>>asList(uk.co.techblue.cgh.dnap.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.co.techblue.cgh.dnap.tables.Databasechangeloglock as(java.lang.String alias) {
		return new uk.co.techblue.cgh.dnap.tables.Databasechangeloglock(alias);
	}
}
