/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Databasechangelog extends org.jooq.impl.TableImpl<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord> {

	private static final long serialVersionUID = 784541244;

	/**
	 * The singleton instance of <code>cgh-processor.DATABASECHANGELOG</code>
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Databasechangelog DATABASECHANGELOG = new uk.co.techblue.cgh.dnap.tables.Databasechangelog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord> getRecordType() {
		return uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord.class;
	}

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.ID</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(63), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.AUTHOR</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> AUTHOR = createField("AUTHOR", org.jooq.impl.SQLDataType.VARCHAR.length(63), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.FILENAME</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> FILENAME = createField("FILENAME", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.DATEEXECUTED</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.sql.Timestamp> DATEEXECUTED = createField("DATEEXECUTED", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.ORDEREXECUTED</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.Integer> ORDEREXECUTED = createField("ORDEREXECUTED", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.EXECTYPE</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> EXECTYPE = createField("EXECTYPE", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.MD5SUM</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> MD5SUM = createField("MD5SUM", org.jooq.impl.SQLDataType.VARCHAR.length(35), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.DESCRIPTION</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.COMMENTS</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> COMMENTS = createField("COMMENTS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.TAG</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> TAG = createField("TAG", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cgh-processor.DATABASECHANGELOG.LIQUIBASE</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord, java.lang.String> LIQUIBASE = createField("LIQUIBASE", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * Create a <code>cgh-processor.DATABASECHANGELOG</code> table reference
	 */
	public Databasechangelog() {
		super("DATABASECHANGELOG", uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR);
	}

	/**
	 * Create an aliased <code>cgh-processor.DATABASECHANGELOG</code> table reference
	 */
	public Databasechangelog(java.lang.String alias) {
		super(alias, uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR, uk.co.techblue.cgh.dnap.tables.Databasechangelog.DATABASECHANGELOG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord> getPrimaryKey() {
		return uk.co.techblue.cgh.dnap.Keys.KEY_DATABASECHANGELOG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.DatabasechangelogRecord>>asList(uk.co.techblue.cgh.dnap.Keys.KEY_DATABASECHANGELOG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.co.techblue.cgh.dnap.tables.Databasechangelog as(java.lang.String alias) {
		return new uk.co.techblue.cgh.dnap.tables.Databasechangelog(alias);
	}
}
