/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Regionintensityreference extends org.jooq.impl.TableImpl<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord> {

	private static final long serialVersionUID = -332927761;

	/**
	 * The singleton instance of <code>cgh-processor.regionintensityreference</code>
	 */
	public static final uk.co.techblue.cgh.dnap.tables.Regionintensityreference REGIONINTENSITYREFERENCE = new uk.co.techblue.cgh.dnap.tables.Regionintensityreference();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord> getRecordType() {
		return uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord.class;
	}

	/**
	 * The column <code>cgh-processor.regionintensityreference.RegionIntensityId</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Long> REGIONINTENSITYID = createField("RegionIntensityId", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.RegionId</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Long> REGIONID = createField("RegionId", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MeanGreenSignal</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEANGREENSIGNAL = createField("MeanGreenSignal", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MedianGreenSignal</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEDIANGREENSIGNAL = createField("MedianGreenSignal", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MeanRedSignal</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEANREDSIGNAL = createField("MeanRedSignal", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MedianRedSignal</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEDIANREDSIGNAL = createField("MedianRedSignal", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MeanLogRatio</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEANLOGRATIO = createField("MeanLogRatio", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.MedianLogRatio</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Double> MEDIANLOGRATIO = createField("MedianLogRatio", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>cgh-processor.regionintensityreference.ArrayId</code>. 
	 */
	public final org.jooq.TableField<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Long> ARRAYID = createField("ArrayId", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>cgh-processor.regionintensityreference</code> table reference
	 */
	public Regionintensityreference() {
		super("regionintensityreference", uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR);
	}

	/**
	 * Create an aliased <code>cgh-processor.regionintensityreference</code> table reference
	 */
	public Regionintensityreference(java.lang.String alias) {
		super(alias, uk.co.techblue.cgh.dnap.CghProcessor.CGH_PROCESSOR, uk.co.techblue.cgh.dnap.tables.Regionintensityreference.REGIONINTENSITYREFERENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord, java.lang.Long> getIdentity() {
		return uk.co.techblue.cgh.dnap.Keys.IDENTITY_REGIONINTENSITYREFERENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord> getPrimaryKey() {
		return uk.co.techblue.cgh.dnap.Keys.KEY_REGIONINTENSITYREFERENCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.co.techblue.cgh.dnap.tables.records.RegionintensityreferenceRecord>>asList(uk.co.techblue.cgh.dnap.Keys.KEY_REGIONINTENSITYREFERENCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.co.techblue.cgh.dnap.tables.Regionintensityreference as(java.lang.String alias) {
		return new uk.co.techblue.cgh.dnap.tables.Regionintensityreference(alias);
	}
}
