/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public interface IAudit extends java.io.Serializable {

	/**
	 * Setter for <code>cgh-processor.audit.audit_id</code>. 
	 */
	public void setAuditId(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.audit.audit_id</code>. 
	 */
	public java.lang.Long getAuditId();

	/**
	 * Setter for <code>cgh-processor.audit.filename</code>. 
	 */
	public void setFilename(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.audit.filename</code>. 
	 */
	public java.lang.String getFilename();

	/**
	 * Setter for <code>cgh-processor.audit.processed_date</code>. 
	 */
	public void setProcessedDate(java.sql.Timestamp value);

	/**
	 * Getter for <code>cgh-processor.audit.processed_date</code>. 
	 */
	public java.sql.Timestamp getProcessedDate();

	/**
	 * Setter for <code>cgh-processor.audit.processed</code>. 
	 */
	public void setProcessed(java.lang.Boolean value);

	/**
	 * Getter for <code>cgh-processor.audit.processed</code>. 
	 */
	public java.lang.Boolean getProcessed();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAudit
	 */
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IAudit from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAudit
	 */
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IAudit> E into(E into);
}
