/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public interface IBaselineaverages extends java.io.Serializable {

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	public void setBaselineaveragesid(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BaselineAveragesId</code>. 
	 */
	public java.lang.Long getBaselineaveragesid();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	public void setRegionid(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.RegionId</code>. 
	 */
	public java.lang.Long getRegionid();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	public void setBmeangreensignal(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignal</code>. 
	 */
	public java.lang.Double getBmeangreensignal();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	public void setBmeangreensignalsd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD</code>. 
	 */
	public java.lang.Double getBmeangreensignalsd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	public void setBmediangreensignal(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignal</code>. 
	 */
	public java.lang.Double getBmediangreensignal();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	public void setBmediangreensignalsd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD</code>. 
	 */
	public java.lang.Double getBmediangreensignalsd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	public void setBmeanredsignal(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignal</code>. 
	 */
	public java.lang.Double getBmeanredsignal();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	public void setBmeanredsignalsd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD</code>. 
	 */
	public java.lang.Double getBmeanredsignalsd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	public void setBmedianredsignal(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignal</code>. 
	 */
	public java.lang.Double getBmedianredsignal();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	public void setBmedianredsignalsd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD</code>. 
	 */
	public java.lang.Double getBmedianredsignalsd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	public void setBmeanlogratio(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatio</code>. 
	 */
	public java.lang.Double getBmeanlogratio();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	public void setBmeanlogratiosd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD</code>. 
	 */
	public java.lang.Double getBmeanlogratiosd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	public void setBmedianlogratio(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatio</code>. 
	 */
	public java.lang.Double getBmedianlogratio();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	public void setBmedianlogratiosd(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD</code>. 
	 */
	public java.lang.Double getBmedianlogratiosd();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignal_M</code>. 
	 */
	public void setBmeangreensignalM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignal_M</code>. 
	 */
	public java.lang.Double getBmeangreensignalM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD_M</code>. 
	 */
	public void setBmeangreensignalsdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanGreenSignalSD_M</code>. 
	 */
	public java.lang.Double getBmeangreensignalsdM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignal_M</code>. 
	 */
	public void setBmediangreensignalM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignal_M</code>. 
	 */
	public java.lang.Double getBmediangreensignalM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD_M</code>. 
	 */
	public void setBmediangreensignalsdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianGreenSignalSD_M</code>. 
	 */
	public java.lang.Double getBmediangreensignalsdM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignal_M</code>. 
	 */
	public void setBmeanredsignalM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignal_M</code>. 
	 */
	public java.lang.Double getBmeanredsignalM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD_M</code>. 
	 */
	public void setBmeanredsignalsdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanRedSignalSD_M</code>. 
	 */
	public java.lang.Double getBmeanredsignalsdM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignal_M</code>. 
	 */
	public void setBmedianredsignalM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignal_M</code>. 
	 */
	public java.lang.Double getBmedianredsignalM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD_M</code>. 
	 */
	public void setBmedianredsignalsdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianRedSignalSD_M</code>. 
	 */
	public java.lang.Double getBmedianredsignalsdM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatio_M</code>. 
	 */
	public void setBmeanlogratioM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatio_M</code>. 
	 */
	public java.lang.Double getBmeanlogratioM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD_M</code>. 
	 */
	public void setBmeanlogratiosdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMeanLogRatioSD_M</code>. 
	 */
	public java.lang.Double getBmeanlogratiosdM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatio_M</code>. 
	 */
	public void setBmedianlogratioM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatio_M</code>. 
	 */
	public java.lang.Double getBmedianlogratioM();

	/**
	 * Setter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD_M</code>. 
	 */
	public void setBmedianlogratiosdM(java.lang.Double value);

	/**
	 * Getter for <code>cgh-processor.baselineaverages.BMedianLogRatioSD_M</code>. 
	 */
	public java.lang.Double getBmedianlogratiosdM();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IBaselineaverages
	 */
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IBaselineaverages
	 */
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IBaselineaverages> E into(E into);
}
