/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public interface IDatabasechangeloglock extends java.io.Serializable {

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOGLOCK.ID</code>. 
	 */
	public void setId(java.lang.Integer value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOGLOCK.ID</code>. 
	 */
	public java.lang.Integer getId();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKED</code>. 
	 */
	public void setLocked(java.lang.Byte value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKED</code>. 
	 */
	public java.lang.Byte getLocked();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKGRANTED</code>. 
	 */
	public void setLockgranted(java.sql.Timestamp value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKGRANTED</code>. 
	 */
	public java.sql.Timestamp getLockgranted();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKEDBY</code>. 
	 */
	public void setLockedby(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOGLOCK.LOCKEDBY</code>. 
	 */
	public java.lang.String getLockedby();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IDatabasechangeloglock
	 */
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangeloglock from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IDatabasechangeloglock
	 */
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangeloglock> E into(E into);
}
