/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public interface IDatabasechangelog extends java.io.Serializable {

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.ID</code>. 
	 */
	public void setId(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.ID</code>. 
	 */
	public java.lang.String getId();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.AUTHOR</code>. 
	 */
	public void setAuthor(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.AUTHOR</code>. 
	 */
	public java.lang.String getAuthor();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.FILENAME</code>. 
	 */
	public void setFilename(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.FILENAME</code>. 
	 */
	public java.lang.String getFilename();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.DATEEXECUTED</code>. 
	 */
	public void setDateexecuted(java.sql.Timestamp value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.DATEEXECUTED</code>. 
	 */
	public java.sql.Timestamp getDateexecuted();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.ORDEREXECUTED</code>. 
	 */
	public void setOrderexecuted(java.lang.Integer value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.ORDEREXECUTED</code>. 
	 */
	public java.lang.Integer getOrderexecuted();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.EXECTYPE</code>. 
	 */
	public void setExectype(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.EXECTYPE</code>. 
	 */
	public java.lang.String getExectype();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.MD5SUM</code>. 
	 */
	public void setMd5sum(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.MD5SUM</code>. 
	 */
	public java.lang.String getMd5sum();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.DESCRIPTION</code>. 
	 */
	public void setDescription(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.DESCRIPTION</code>. 
	 */
	public java.lang.String getDescription();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.COMMENTS</code>. 
	 */
	public void setComments(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.COMMENTS</code>. 
	 */
	public java.lang.String getComments();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.TAG</code>. 
	 */
	public void setTag(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.TAG</code>. 
	 */
	public java.lang.String getTag();

	/**
	 * Setter for <code>cgh-processor.DATABASECHANGELOG.LIQUIBASE</code>. 
	 */
	public void setLiquibase(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.DATABASECHANGELOG.LIQUIBASE</code>. 
	 */
	public java.lang.String getLiquibase();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IDatabasechangelog
	 */
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangelog from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IDatabasechangelog
	 */
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IDatabasechangelog> E into(E into);
}
