/**
 * This class is generated by jOOQ
 */
package uk.co.techblue.cgh.dnap.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked" })
public interface IRegion extends java.io.Serializable {

	/**
	 * Setter for <code>cgh-processor.region.RegionID</code>. 
	 */
	public void setRegionid(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.region.RegionID</code>. 
	 */
	public java.lang.Long getRegionid();

	/**
	 * Setter for <code>cgh-processor.region.Chromosome</code>. 
	 */
	public void setChromosome(java.lang.String value);

	/**
	 * Getter for <code>cgh-processor.region.Chromosome</code>. 
	 */
	public java.lang.String getChromosome();

	/**
	 * Setter for <code>cgh-processor.region.StartPosition</code>. 
	 */
	public void setStartposition(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.region.StartPosition</code>. 
	 */
	public java.lang.Long getStartposition();

	/**
	 * Setter for <code>cgh-processor.region.StopPosition</code>. 
	 */
	public void setStopposition(java.lang.Long value);

	/**
	 * Getter for <code>cgh-processor.region.StopPosition</code>. 
	 */
	public java.lang.Long getStopposition();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IRegion
	 */
	public void from(uk.co.techblue.cgh.dnap.tables.interfaces.IRegion from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IRegion
	 */
	public <E extends uk.co.techblue.cgh.dnap.tables.interfaces.IRegion> E into(E into);
}
